// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEFs-9JbXrhml5fDmTIRtCtzOMWGRdy6Y',
    appId: '1:1082345528400:web:b051fb0be92f4bc8848555',
    messagingSenderId: '1082345528400',
    projectId: 'motiontodo8-97322',
    authDomain: 'motiontodo8-97322.firebaseapp.com',
    storageBucket: 'motiontodo8-97322.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmVo_Ynkv8M6Lvx4LBkY-A1ZWwU9N9E7o',
    appId: '1:1082345528400:android:66cc2574b64a8d46848555',
    messagingSenderId: '1082345528400',
    projectId: 'motiontodo8-97322',
    storageBucket: 'motiontodo8-97322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBluHrY7WTVlOWnrXgRswIZ6-gT_ecT_tM',
    appId: '1:1082345528400:ios:8e6cb28c830e3d3a848555',
    messagingSenderId: '1082345528400',
    projectId: 'motiontodo8-97322',
    storageBucket: 'motiontodo8-97322.firebasestorage.app',
    iosBundleId: 'com.example.week8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBluHrY7WTVlOWnrXgRswIZ6-gT_ecT_tM',
    appId: '1:1082345528400:ios:8e6cb28c830e3d3a848555',
    messagingSenderId: '1082345528400',
    projectId: 'motiontodo8-97322',
    storageBucket: 'motiontodo8-97322.firebasestorage.app',
    iosBundleId: 'com.example.week8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEFs-9JbXrhml5fDmTIRtCtzOMWGRdy6Y',
    appId: '1:1082345528400:web:c18b67c139ab6194848555',
    messagingSenderId: '1082345528400',
    projectId: 'motiontodo8-97322',
    authDomain: 'motiontodo8-97322.firebaseapp.com',
    storageBucket: 'motiontodo8-97322.firebasestorage.app',
  );
}
